name: docker-registry

on:
  push:
    branches:
      - "main"

jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}
          tag_with_ref: true
          tags: ${{ github.sha }}
    